export const GET_PHRASE_START = 'GET_PHRASE_START'
export const GET_PHRASE_SUCCESS = 'GET_PHRASE_SUCCESS'
export const GET_PHRASE_FAILED = 'GET_PHRASE_FAILED'

export const PUT_PHRASE_START = 'PUT_PHRASE_START'
export const PUT_PHRASE_SUCCESS = 'PUT_PHRASE_SUCCESS'
export const PUT_PHRASE_FAILED = 'PUT_PHRASE_FAILED'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const DELETE_START = 'DELETE_START'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAILED = 'DELETE_FAILED'

